tproxy-port: 7893
bind-address: '*'
mode: rule
allow-lan: true
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
  fallback:
    - https://dns.google/dns-query  
proxies:
proxy-groups:
  - name: anggur
    type: select
    use:
      - Accounting
    proxies:
      - DIRECT
  - name: indonesia
    type: select
    use:
      - Accounting
    proxies:
      - DIRECT
  - name: sosial media
    type: select
    use:
      - Accounting
    proxies:
      - DIRECT
  - name: streaming
    type: select
    use:
      - Accounting
    proxies:
      - DIRECT
  - name: ads block
    type: select
    proxies:    
      - DIRECT
      - REJECT
proxy-providers:
  Accounting:
    type: file
    path: ./confs/config.yaml
    health-check:
     enable: true
     interval: 600
     url: http://www.gstatic.com/generate_204
rule-providers:
  ads block:
    type: http
    behavior: domain
    url: "https://bit.ly/3mhQskP"
    path: ./confs/rules/reject.yaml
    interval: 86400
  private block:
    type: http
    behavior: classical
    path: ./confs/rules/block.yaml
    url: "https://github.com/mjeeClover/ClashConfig/raw/main/Proxy%20Provider%20(http)/confs/rules/block.yaml"
    path: ./confs/rules/reject.yaml
    interval: 86400
  indonesia:
    type: http
    behavior: classical
    path: ./confs/rules/Indonesia.yaml
    url: "https://github.com/mjeeClover/ClashConfig/raw/main/Proxy%20Provider%20(http)/confs/rules/Indonesia.yaml"
    path: ./confs/rules/reject.yaml
    interval: 86400    
  sosial media:
    type: http
    behavior: classical
    path: ./confs/rules/sosial.yaml
    url: "https://github.com/mjeeClover/ClashConfig/raw/main/Proxy%20Provider%20(http)/confs/rules/sosial.yaml"
    path: ./confs/rules/reject.yaml
    interval: 86400
  streaming:
    type: http
    behavior: classical
    path: ./confs/rules/streaming.yaml
    url: "https://github.com/mjeeClover/ClashConfig/raw/main/Proxy%20Provider%20(http)/confs/rules/streaming.yaml"
    path: ./confs/rules/reject.yaml
    interval: 86400
rules:
  - RULE-SET,ads block,ads block
  - RULE-SET,private block,ads block
  - RULE-SET,indonesia,indonesia
  - RULE-SET,sosial media,sosial media
  - RULE-SET,streaming,streaming
  - MATCH,anggur
