port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7894
tproxy-port: 7893
bind-address: '*'
mode: rule
allow-lan: true
log-level: silent
external-controller: 127.0.0.1:9090
external-ui: dashboard
interface-name: en0
experimental:
  ignore-resolve-fail: true
ipv6: true
profile:
  store-selected: true
  tracing: true
dns:
    enable: false
    listen: 0.0.0.0:1053
    ipv6: true
    enhanced-mode: redir-host # redir-host or fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver:
      - 8.8.8.8
proxies:
(Akun)

proxy-groups:
  - name: browsingさ☘
    type: select
    proxies: 
      - trojanそれsocksさ☘
      - vlessそれvmessさ☘
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./premium/rule/reject.yaml
    interval: 86400
    
rules:
  - RULE-SET,reject,REJECT
  - GEOIP,ID,browsingさ☘
  - MATCH,browsingさ☘
 
 
